
# Getting Started {.unnumbered}

This guide will help you install TermiPy and get familiar with its basic usage.

## Installation

You can install TermiPy using pip, the Python package installer:

```bash
pip install termipy
```

Visit PyPi for more releases - https://pypi.org/project/termipy/

## Running TermiPy

After installation, you can start TermiPy by running:

```bash
termipy
```

If you encounter any PATH issues, you can use:

```bash
PATH="/usr/bin:/usr/local/bin" termipy
```

## Basic Usage

Once TermiPy is running, you'll see the TermiPy prompt:

```bash
@termipy >>
```

You can now start entering commands. Here are some basic commands to get you started:

1. **echo `<message>`**: Print a message to the terminal

    ```bash
    @termipy >> echo Hello, TermiPy!
    ```


2. **getwd** or **ls**: Get current working directory

    ```bash
    @termipy >> getwd
    ```


3. **setwd `<directory>`**: Change directory

    ```bash
    @termipy >> setwd /path/to/directory
    ```


4. **typeof `<command>`**: Show command type

    ```bash
    @termipy >> typeof echo
    ```


5. **clear** (aliases: **cls**, **clr**): Clear the screen

    ```bash
    @termipy >> clear
    ```


6. **tree [directory]**: Show directory structure

    ```bash
    @termipy >> tree
    ```


7. **help**: Display help information

    ```bash
    @termipy >> help
    ```


8. **exit**: Exit TermiPy

    ```bash
    @termipy >> exit
    ```


For a full list of available commands, use the `commands` command:

```bash
@termipy >> commands
```

## Next Steps

- Explore [File Handling](file-handling.qmd) operations.
- Learn about [Setting Up Environments](setting-environment.qmd).
- Explore [Resource Monitoring](resource-stats.qmd).
- Check out the [About](about.qmd) for more documentation and support.
